# Create a deployment yaml file for the app

# This file defines a Kubernetes deployment for an application
# with 3 replicas, using the image princestanley/github-copilot:latest
# and exposing port 8080. It also sets resource requests and limits
# for memory and CPU usage.
# The deployment will be created in the default namespace.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: princestanley/github-copilot:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"